DEFAULT_SKILLS = [
    "python",
    "java",
    "javascript",
    "typescript",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "data science",
    "data analysis",
    "data visualization",
    "statistics",
    "natural language processing",
    "computer vision",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "excel",
    "power bi",
    "tableau",
    "html",
    "css",
    "react",
    "angular",
    "vue.js",
    "node.js",
    "express.js",
    "django",
    "flask",
    "fastapi",
    "spring boot",
    "git",
    "github",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "google cloud platform",
    "linux",
    "ci/cd",
]


SKILL_ALIASES = {
    "js": "javascript",
    "ts": "typescript",
    "nodejs": "node.js",
    "node js": "node.js",
    "ml": "machine learning",
    "dl": "deep learning",
    "ai": "artificial intelligence",
    "nlp": "natural language processing",
    "cv": "computer vision",
    "postgres": "postgresql",
    "mongo": "mongodb",
    "sklearn": "scikit-learn",
    "tf": "tensorflow",
    "powerbi": "power bi",
    "reactjs": "react",
    "vuejs": "vue.js",
    "expressjs": "express.js",
    "k8s": "kubernetes",
    "gcp": "google cloud platform",
    "cicd": "ci/cd",
    "continuous integration": "ci/cd",
    "continuous deployment": "ci/cd",
}